name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@c12583777ecdfd3be55c69cf75464299dc01057e # v3
        with:
          generate_release_notes: true
